"""
Django settings for runsheet project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""


from pathlib import Path
from decouple import AutoConfig

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nf+r2a64i1@%oi#rj&nj4%r-7twx&0tuig(g1q7v)i13-5h*be'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['*']

# ENV
config = AutoConfig()

API_USER = config('API_USER')
API_PASS = config('API_PASS')
BASE_URL_WEASYPRINT = config('BASE_URL_WEASYPRINT')
BASE_URL_ALAYACARE = config('BASE_URL_ALAYACARE')
#PDF_LOGO_URL = config('PDF_LOGO_URL')
#CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS')
DEV_PHASE = config('DEV_PHASE')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'agency',
    'bootstrap4',
    'crispy_forms',
    'cims',
    'django.contrib.humanize',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

CRISPY_FAIL_SILENTLY = not DEBUG

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    #'cims.middleware.ProxyRemoteUserMiddleware',
    'cims.middleware.RemoteUserHeaderMiddleware',
    'django.contrib.auth.middleware.RemoteUserMiddleware', #added for remote user passthrough from IIS
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

AUTHENTICATION_BACKENDS = [
    #'cims.auth.ProxyRemoteUserBackend',
    'django.contrib.auth.backends.RemoteUserBackend', #added for remote user passthrough from IIS
]

ROOT_URLCONF = 'runsheet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR.joinpath('templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'runsheet.wsgi.application'
ASGI_APPLICATION = 'runsheet.asgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django_snowflake',
        'NAME': 'D4BBC046-8051-452C-9D09-AE61D5C11532',
        'USER': 'D4BBC046-8051-452C-9D09-AE61D5C11532',
        'PASSWORD': 'Ge4sEMiOTEi4WL5yMAN1r9ezvVkujMw#p6PqLn2hlNYwdlFb$uOSyDFQZlhyLL61s',
        'ACCOUNT': 'll54557.ap-southeast-2',  # usually in the form "<organization>-<cloud region>"
        'WAREHOUSE': 'D4BBC046-8051-452C-9D09-AE61D5C11532',
        'SCHEMA': 'D4BBC046-8051-452C-9D09-AE61D5C11532',
        'ROLE': 'D4BBC046-8051-452C-9D09-AE61D5C11532',  # specify your read-only role
        'OPTIONS': {
            'client_session_keep_alive': True,  # Keeps session alive
        },
    },
    'mssql_broken': {
        'ENGINE': 'mssql',
        'NAME': 'DTDev',
        'HOST': 'ef01dbs3b',
        'PORT': '1433',  # Default SQL Server port
        #'USER': 'ARCHBNE\\welshs',
        #'PASSWORD': 'REDACTED',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'trusted_connection': 'yes'
            #'extra_params': 'encrypt=yes;trustservercertificate=yes',  # Optional
        },
    },
    'mssql': {
        'ENGINE': 'mssql',
        'NAME': 'sub',
        'USER': 'sub',
        'PASSWORD': 'U333',
        'HOST': 'EF01TST1A',
        'PORT': '1433',  
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params':'Encrypt=yes;TrustServerCertificate=yes;',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Australia/Brisbane'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
    ]

# Upload files (CSV for CIMS payfile audit and corrections)

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# (optional) keep uploads reasonable
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB in-memory POST limit
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024   # 5 MB in-memory file limit

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if DEV_PHASE == 'TEST':
    CSRF_TRUSTED_ORIGINS = ['https://ef01tst1a.catholic.net.au']
elif DEV_PHASE == 'PROD':
    CSRF_TRUSTED_ORIGINS = ['https://rostering.catholic.net.au']
else:
    CSRF_TRUSTED_ORIGINS = ['http://localhost:8000','http://localhost']
